further progress on new unwinder
git-svn-id: svn+ssh://svn.cprover.org/var/lib/cvs/software/deltacheck/branches/termination@1475 ae12b94c-7a1e-481b-bb16-7d291d499974

diff --git a/regression/graphml/Makefile b/regression/graphml/Makefile
--- a/regression/graphml/Makefile
+++ b/regression/graphml/Makefile
@@ -1,9 +1,35 @@
-FLAGS = --k-induction --competition-mode
+FLAGS = --k-induction --competition-mode --32
+#FLAGS = --unwind 11 --no-unwinding-assertions
 2LS = ../../../src/summarizer/2ls 
 #2LS = $W/svncprover/trunk/src/cbmc/cbmc
 CPACHECKER = $W/svncpachecker
+ULTIMATE = $W/UltimateAutomizer
 
-test:
+test: test-ultimate
+
+test-ultimate:
+	@PWD=`pwd`; \
+	for dir in `find $$PWD/* -maxdepth 1 -type d`; do \
+	  cd $$dir; \
+	  rm cex.graphml; \
+	  $(2LS) main.c $(FLAGS) --graphml-cex cex.graphml > main.out; \
+          cd $(ULTIMATE); \
+          python3 ./UltimateWitnessChecker.py \
+            $$dir/../PropertyERROR.prp \
+            $$dir/main.c 32bit precise \
+            $$dir/cex.graphml \
+            >> $$dir/main.out 2>&1; \
+          cd $$dir; \
+          tail -n 3 main.out | grep FALSE > /dev/null; \
+	  if [ "$$?" -eq 0 ]; then \
+            echo $$dir "[PASSED]"; \
+          else \
+            echo $$dir "[FAILED]"; \
+           fi; \
+	  cd ..; \
+	done;
+
+test-cpachecker:
 	@PWD=`pwd`; \
 	for dir in `find $$PWD/* -maxdepth 1 -type d`; do \
 	  cd $$dir; \
